#!/bin/sh

set -e

lb config noauto \
	--apt-recommends false \
	--archive-areas "main contrib non-free non-free-firmware" \
	--apt-indices false \
	--debian-installer live \
	--debian-installer-gui false \
	--debian-installer-distribution trixie \
	--distribution trixie \
	--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
	--image-name gila-070325 \
	--iso-volume gila-070325 \
	--memtest none \
	--win32-loader false \
	--zsync false \
	"${@}"
